import React from "react";
import { LOGO_COMPONENTS } from "./logos/index.js";

// Partner/network/stablecoin marks are inlined as real React SVG
// components (generated by `npm run generate:logos`, see
// scripts/generate-partner-logos.mjs) rather than loaded from a file via
// `new URL(..., import.meta.url)`. A dynamic, templated `new URL()` call
// can't be statically resolved by most bundlers (Webpack/Next.js won't copy
// the asset at all; even Vite only handles literal, non-templated paths),
// so consumers built with those tools would see a broken <img>. Inlining
// the SVG removes the asset-resolution step entirely, so it renders
// correctly regardless of the consuming app's bundler.

function bankLogo(Component) {
  function BankLogo({ size, className = "", style }) {
    return (
      <Component
        width={size * 1.6}
        height={size}
        aria-hidden="true"
        focusable="false"
        className={className}
        style={style}
      />
    );
  }
  return BankLogo;
}

function squareLogo(Component) {
  function SquareLogo({ size, className = "", style }) {
    return (
      <Component
        width={size}
        height={size}
        aria-hidden="true"
        focusable="false"
        className={className}
        style={style}
      />
    );
  }
  return SquareLogo;
}

const KNOWN_COINS = ["xsgd", "xusd", "xidr", "usdc", "usdt"];
const KNOWN_BANKS = [
  "uob",
  "anz",
  "dbs",
  "standard-chartered",
  "smbc",
  "mandiri",
  "rhb",
  "cimb",
  "bss",
  "cimb-niaga",
  "bni",
  "hana-bank",
  "bri",
  "permata",
  "bca",
  "danamon",
  "bsi",
];
const KNOWN_CHAINS = [
  "ethereum",
  "arbitrum",
  "polygon",
  "metamask",
  "bsc",
  "avalanche",
  "tron",
  "ripple",
  "zilliqa",
  "solana",
  "base",
  "walletconnect",
  "hedera",
];
const KNOWN_PARTNERS = [
  "binance",
  "crypto-com",
  "zillet",
  "qcp-capital",
  "fireblocks",
  "onchain-custodian",
  "uniswap",
  "dextf",
  "coinhako",
  "liquid",
  "tokenize-xchange",
  "bitgo",
  "ledger-vault",
  "unagii",
  "coinstore",
];

// Banks render as a wide lockup (size * 1.6 x size); everything else
// (coins, chains, exchanges/custodians) renders as a square mark. Built
// from LOGO_COMPONENTS so newly generated logos only need registering in
// one of the KNOWN_* category arrays above.
const LOGOS = {};
for (const slug of KNOWN_BANKS) {
  if (LOGO_COMPONENTS[slug]) LOGOS[slug] = bankLogo(LOGO_COMPONENTS[slug]);
}
for (const slug of [...KNOWN_COINS, ...KNOWN_CHAINS, ...KNOWN_PARTNERS]) {
  if (LOGO_COMPONENTS[slug]) LOGOS[slug] = squareLogo(LOGO_COMPONENTS[slug]);
}

function prettify(slug) {
  return slug.replace(/-/g, " ").replace(/\b\w/g, (c) => c.toUpperCase());
}

export function PartnerLogo({ name, size = 32, monochrome = true, className = "", style }) {
  const Custom = LOGOS[name];
  if (Custom) return <Custom size={size} className={className} style={style} />;

  // Fallback monochrome wordmark pill — shown for names not yet registered
  // with a licensed logo asset. PartnerLogo marks themselves are licensed
  // full-color brand assets and are intentionally never recolored;
  // `monochrome` only affects this fallback pill.
  const bg = monochrome ? "transparent" : "var(--surface-secondary)";
  const fg = monochrome ? "var(--text-primary)" : "var(--text-primary)";
  return (
    <span
      className={"partner-logo " + className}
      title={prettify(name)}
      style={{
        display: "inline-flex",
        alignItems: "center",
        height: size,
        padding: `0 ${Math.max(8, size / 3)}px`,
        background: bg,
        border: `1px solid var(--border)`,
        borderRadius: 4,
        font: `700 ${Math.max(10, size / 2.7)}px/1 var(--font-display)`,
        color: fg,
        letterSpacing: "0.04em",
        textTransform: "uppercase",
        whiteSpace: "nowrap",
        ...style,
      }}
    >
      {prettify(name)}
    </span>
  );
}

PartnerLogo.coins = KNOWN_COINS;
PartnerLogo.banks = KNOWN_BANKS;
PartnerLogo.chains = KNOWN_CHAINS;
PartnerLogo.partners = KNOWN_PARTNERS;
