import React, { useRef } from "react";
import { Modal, type ModalRootProps } from "../Modal";
import { Button } from "../Button";
import { cn } from "../../lib/cn";
import "./Modal2FA.css";

export type Modal2FAProps = Omit<ModalRootProps, "children"> & {
  /** Current code (digits only) */
  value?: string;
  /** Called with the new code as digits are typed or pasted */
  onValueChange?: (value: string) => void;
  /** Verify button handler */
  onVerify?: () => void;
  /** Number of code digits */
  length?: number;
  title?: React.ReactNode;
  instruction?: React.ReactNode;
  /** Text for the trouble link; pass an empty value to hide it */
  troubleText?: React.ReactNode;
  onTrouble?: () => void;
  /** Illustration shown above the title */
  illustration?: React.ReactNode;
  verifyLabel?: React.ReactNode;
  cancelLabel?: React.ReactNode;
  /** Defaults to `true` until all digits are entered */
  verifyDisabled?: boolean;
  /** Class names for the modal panel */
  className?: string;
};

/** 2FA modal: illustration + instruction + segmented code input, composed from Modal. */
export function Modal2FA({
  value = "",
  onValueChange,
  onVerify,
  length = 6,
  title = "2-Factor Authentication",
  instruction = "Enter the 6-digit code generated by your Two-factor Authentication (2FA) app.",
  troubleText = "Having trouble with authenticator?",
  onTrouble,
  illustration,
  verifyLabel = "Verify",
  cancelLabel = "Cancel",
  verifyDisabled,
  className,
  ...rootProps
}: Modal2FAProps) {
  const inputs = useRef<Array<HTMLInputElement | null>>([]);

  const setDigit = (idx: number, digit: string) => {
    const next = value.split("");
    next[idx] = digit;
    onValueChange?.(next.join("").slice(0, length));
  };

  const handleChange = (idx: number) => (e: React.ChangeEvent<HTMLInputElement>) => {
    const raw = e.target.value.replace(/\D/g, "");
    if (!raw) {
      setDigit(idx, "");
      return;
    }
    // Support paste of full code.
    if (raw.length > 1) {
      onValueChange?.((value.slice(0, idx) + raw).slice(0, length));
      inputs.current[Math.min(idx + raw.length, length - 1)]?.focus();
      return;
    }
    setDigit(idx, raw);
    if (idx < length - 1) inputs.current[idx + 1]?.focus();
  };

  const handleKeyDown = (idx: number) => (e: React.KeyboardEvent<HTMLInputElement>) => {
    if (e.key === "Backspace" && !value[idx] && idx > 0) {
      inputs.current[idx - 1]?.focus();
    }
  };

  const isVerifyDisabled = verifyDisabled ?? value.length < length;

  return (
    <Modal.Root {...rootProps}>
      <Modal.Popup size="small" className={cn("tfa", className)}>
        <Modal.Header>
          <Modal.Close />
        </Modal.Header>
        <Modal.Body>
          <div className="tfa__hero">
            {illustration && (
              <Modal.Illustration className="tfa__illustration" aria-hidden="true">
                {illustration}
              </Modal.Illustration>
            )}
            <Modal.Title className="tfa__title">{title}</Modal.Title>
          </div>
          {instruction && (
            <Modal.Description className="tfa__instruction">{instruction}</Modal.Description>
          )}
          <div className="tfa__code" role="group" aria-label="Authentication code">
            {Array.from({ length }).map((_, i) => (
              <input
                key={i}
                ref={(el) => {
                  inputs.current[i] = el;
                }}
                className="tfa__digit"
                type="text"
                inputMode="numeric"
                autoComplete={i === 0 ? "one-time-code" : "off"}
                maxLength={1}
                aria-label={`Digit ${i + 1}`}
                value={value[i] ?? ""}
                onChange={handleChange(i)}
                onKeyDown={handleKeyDown(i)}
              />
            ))}
          </div>
          {troubleText && (
            <button type="button" className="tfa__trouble" onClick={onTrouble}>
              {troubleText}
            </button>
          )}
        </Modal.Body>
        <Modal.Footer>
          <Modal.Close render={<Button variant="secondary" size="lg" className="tfa__action" />}>
            {cancelLabel}
          </Modal.Close>
          <Button
            variant="primary"
            size="lg"
            className="tfa__action"
            onClick={onVerify}
            disabled={isVerifyDisabled}
          >
            {verifyLabel}
          </Button>
        </Modal.Footer>
      </Modal.Popup>
    </Modal.Root>
  );
}
