import React from "react";
import type { Meta, StoryObj } from "@storybook/react-vite";
import { Modal2FA } from "./Modal2FA";
import { Button } from "../Button";
import { PhoneWithShieldIllustration } from "../Illustration/illustrations/index";

const meta: Meta<typeof Modal2FA> = {
  title: "Patterns/Modal/2FA",
  component: Modal2FA,
  parameters: { layout: "centered" },
  argTypes: {
    title: { control: "text" },
    instruction: { control: "text" },
    verifyLabel: { control: "text" },
    cancelLabel: { control: "text" },
    verifyDisabled: { control: "boolean" },
    onVerify: { action: "onVerify" },
  },
  args: {
    title: "2-Factor Authentication",
    instruction: "Enter the 6-digit code generated by your Two-factor Authentication (2FA) app.",
    verifyLabel: "Verify",
    cancelLabel: "Cancel",
  },
};
export default meta;

type Story = StoryObj<typeof Modal2FA>;

const illustration = <PhoneWithShieldIllustration />;

export const Default: Story = {
  render: function Render(args) {
    const [open, setOpen] = React.useState(false);
    const [code, setCode] = React.useState("");
    return (
      <>
        <Button onClick={() => setOpen(true)}>Open 2FA</Button>
        <Modal2FA
          {...args}
          open={open}
          onOpenChange={setOpen}
          value={code}
          onValueChange={setCode}
          onVerify={() => setOpen(false)}
          illustration={illustration}
        />
      </>
    );
  },
};

export const Open: Story = {
  render: function Render(args) {
    const [code, setCode] = React.useState("123");
    return (
      <Modal2FA
        {...args}
        defaultOpen
        value={code}
        onValueChange={setCode}
        illustration={illustration}
      />
    );
  },
};
