import React, { useState } from "react";
import { Modal2FA } from "./Modal2FA";
import { Button } from "../Button/Button";

export default {
  title: "Patterns/Modal/2FA",
  component: Modal2FA,
  parameters: { layout: "centered" },
  argTypes: {
    open: { control: "boolean" },
    title: { control: "text" },
    instruction: { control: "text" },
    verifyLabel: { control: "text" },
    cancelLabel: { control: "text" },
    verifyDisabled: { control: "boolean" },
    onClose: { action: "onClose" },
    onVerify: { action: "onVerify" },
    onChange: { action: "onChange" },
  },
  args: {
    open: false,
    title: "2-Factor Authentication",
    instruction: "Enter the 6-digit code generated by your Two-factor Authentication (2FA) app.",
    verifyLabel: "Verify",
    cancelLabel: "Cancel",
  },
};

const Illustration = () => (
  <span className="material-symbols-rounded" style={{ fontSize: 96, color: "var(--primary)" }}>
    phonelink_lock
  </span>
);

function Demo(props) {
  const [open, setOpen] = useState(false);
  const [code, setCode] = useState("");
  return (
    <>
      <Button onClick={() => setOpen(true)}>Open 2FA</Button>
      <Modal2FA
        open={open}
        onClose={() => setOpen(false)}
        value={code}
        onChange={setCode}
        onVerify={() => setOpen(false)}
        illustration={<Illustration />}
        {...props}
      />
    </>
  );
}

export const Default = { render: () => <Demo /> };

export const Open = {
  render: () => {
    function Wrapper() {
      const [code, setCode] = useState("123");
      return (
        <Modal2FA
          open
          onClose={() => {}}
          value={code}
          onChange={setCode}
          onVerify={() => {}}
          illustration={<Illustration />}
        />
      );
    }
    return <Wrapper />;
  },
};
